### ISSUE TITLE
Install nubuilder V4

### ISSUE THREAD

**Issue by Marcvander** [nuSoftware/nuBuilder4#13]
Hey,

I've been using nuBuilder v3, and I saw you released this new version. When trying to install it (after editing nuconfig.php), I don't find the nuinstall.php file as in the previous version.

How can I install this new version ?

Thanks

**Comment by tomsx** [comment]
I asked myself the same question and ended up running the sql scripts manually (to be found in nubuilder4.sql).

**Comment by Nurb432** [comment]
Is v4 actually released yet?

**Comment by tomsx** [comment]
I haven't seen a release announcement...so I guess no

**Comment by tomsx** [comment]
http://wiki.nubuilder.net/nubuilderforte/index.php/Setup#Installing_nuBuilder_Forte
