### ISSUE TITLE
License declaration

### ISSUE THREAD

**Issue by ccsmart** [nuSoftware/nuBuilder4#19]
Greetings.
There seems to be no license declaration in the project which makes it hard to verify compliance when intending to use nubuilder.
Can this be clarified in code /repo ?

**Comment by tomsx** [comment]
This is the only thing I have found:

nuBuilder is free to download and install on your own web server **with zero licence fees**.
https://www.nubuilder.com/about

And there used to be a licence page for v3: 
The nuBuilder platform is available to the public under the GNU General Public License version 3 (GPLv3).
https://web.archive.org/web/20170221133542/https://www.nubuilder.net/license.php

**Comment by tomsx** [comment]
A licence file has been added:

https://github.com/nuSoftware/nuBuilder4/blob/master/LICENSE.txt

**Comment by ccsmart** [comment]
perfect, thanks !
